### ISSUE TITLE
Feature: Operational Risk Reduction by Updating Dependencies

### ISSUE THREAD

**Issue by matt3214** [databrickslabs/mosaic#116]
**Is your feature request related to a problem? Please describe.**
We are attempting to bring Mosaic into JFrog Artifactory in order to perform some basic risk assessment using JFrog's XRay scan feature.

When we bring in mosaic 0.1.1 into JFrog and examine the XRay scan results, we see no Security vulnerabilities, but we do see some 'Operation Risk'.

JFrog defines Component Operational Risk to be "...the risk of using outdated or inactive open source software components in your projects" (from the [JFrog Operational Risk page](https://www.jfrog.com/confluence/display/JFROG/Components+Operational+Risk))

The report they generate shows that five packages are 'High' Operational Risk.

These packages are:

com.esri.geometry:esri-geometry-api
com.googlecode.json-simple:json-simple
com.uber:h3
org.locationtech.jts.io:jts-io-common
org.locationtech.jts:jts-core

One of the reasons that these are rated High, is because the release cadence for all five of these packages is less than or equal to one release per year.

Another issue is that 
com.googlecode.json-simple:json-simple
had its last release in December of 2012.

I want to have low operational risk, as defined above, and therefore want to ensure that dependent packages will be maintained and are not abandoned by their authors. 

I recognize and appreciate that two of these packages are deployed by large companies, (Uber, Google) and therefore are probably not going to be abandoned for lack of resources, but I would like to request that these considerations be made by members of the Mosaic Databricks team.

If you were in my shoes, would you find this to be concerning, if not, why not?

**Describe the solution you'd like**
All dependent packages would be selected such that Databricks-Mosaic reports no Operational Risk in JFrog Artifactory XRay Scan.
Some examples _might_ be: 
to replace 
com.googlecode.json-simple:json-simple -> https://mvnrepository.com/artifact/com.github.java-json-tools/json-schema-validator
...

**Describe alternatives you've considered**
Not using Mosaic library in our system.

**Additional context**
See [JFrog Artifactory Operational Risk Page](https://www.jfrog.com/confluence/display/JFROG/Components+Operational+Risk)

**Contributing to Mosaic**
Guidelines for contributing to Mosaic can be found in `CONTRIBUTING.md`.

**Comment by milos-colic** [comment]
@matt3214 Thank you for submitting this report.
I will provide our view on the listed dependencies.

- com.esri.geometry:esri-geometry-api - We use this dependency for geometryAPI. These APIs are relatively stable, geometry math is not evolving rapidly. So having fewer releases and commits is expected for such dependency. It is supported by ESRI. That being said this is not the only geometry API we implement. We can configure the framework to use either esri-geometry-api or jts-core. 
- com.googlecode.json-simple:json-simple - This is a transitive dependency coming from spark itself. There are many other open source projects that depend on it: https://mvnrepository.com/artifact/com.googlecode.json-simple/json-simple/usages. I appreciate this can be perceived as a risk due to no new releases for a long period. But due to the nature of the dependency JSON syntax being stable, and the vast amount of projects using this dependency, we do not believe this dependency will have end of life any time soon. To your point of replacing it, we cannot do it since it is a transitive dependency.
- com.uber:h3 - The H3 index system has stable APIs and has been maintained by UBER. We are adding new index systems as configurable alternatives to the system. In the new releases we plan to add BNG, S2 and geohash. This activity should derisk the H3 as the only current alternative. H3 java api is just their java bindings. The core is implemented in c++ and then recompiled using JNI. This could lead to lower number of releases in java.
- org.locationtech.jts.io:jts-io-common - Very common dependency for GIS systems. Other 3rd party frameworks that operate in GIS domain are likely to use this in combination with jts-core. Similarly to ESRI geometry API, this dependency implements geometry operations and APIs are pretty stable hence fewer releases that expected.
- org.locationtech.jts:jts-core - Same as for jts-io-commons.
Please let me know if these justifications are sufficient, or if you need more clarifications.
Thanks

**Comment by milos-colic** [comment]
There were no communication on this issue for a long time, I will close it.
