### ISSUE TITLE
Get mosaic to work with Databricks Connect

### ISSUE THREAD

**Issue by castillo-luis** [databrickslabs/mosaic#193]
**Is your feature request related to a problem? Please describe.**
Some mosaic functions will not work with databricks connect due to the convert_to helper function that is never registered. Calling any of the geometry constructor/accessor functions that rely on convert_to (ex. st_geomfromgeojson) will fail with an error message that convert_to is not a valid function. Other functions that do not rely on convert_to seem to work fine.

**Describe the solution you'd like**
Have mosaic work with databricks connect.

**Comment by fsaldana-rseg** [comment]
Any updates on getting this functionality included or even a potential temporary workaround to register `convert_to` so that databricks_connect has access.  Running the same st_* functions works fine in a notebook. 

`df_index= df_index.withColumn("the_chip", expr("st_geomfromwkb(ix.wkb)"))`
`df_index.show()`

local-dev_1               | Traceback (most recent call last):
local-dev_1               |   File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3437, in run_code
local-dev_1               |     exec(code_obj, self.user_global_ns, self.user_ns)
local-dev_1               |   File "<ipython-input-2-d171f66feba0>", line 1, in <module>
local-dev_1               |     df_basin_index.count()
local-dev_1               |   File "/usr/local/lib/python3.8/dist-packages/pyspark/sql/dataframe.py", line 688, in count
local-dev_1               |     return int(self._jdf.count())
local-dev_1               |   File "/usr/local/lib/python3.8/dist-packages/py4j/java_gateway.py", line 1304, in __call__
local-dev_1               |     return_value = get_return_value(
local-dev_1               |   File "/usr/local/lib/python3.8/dist-packages/pyspark/sql/utils.py", line 123, in deco
local-dev_1               |     raise converted from None
local-dev_1               | pyspark.sql.utils.AnalysisException: Undefined function: convert_to. This function is neither a built-in/temporary function, nor a persistent function that is qualified as spark_catalog.default.convert_to.; line 1 pos 0

**Comment by edurdevic** [comment]
Thank you for submitting this issue.

Registering this function is not simple, because depending on the second parameter the return type changes (WKB would return binary and WKT a string for example).
So the second parameter needs to be a static string. When registering the expression, both parameters become expressions, so it is not possible determine the return type at query planning time.

This requires some refactoring to decompose the convert_to into multiple functions. 
We have planned to fix it in the coming weeks.

**Comment by fsaldana-rseg** [comment]
Thanks for the timely response. Glad to hear that a fix is in the plans and I am looking forward to the update!

**Comment by edurdevic** [comment]
I think I found the issue.
There was a mismatch between the function name and their SQL representation.
