### ISSUE TITLE
grid_tessellate unable to return any result for a given line string with resolution set to 8

### ISSUE THREAD

**Issue by damianrakowski-tomtom** [databrickslabs/mosaic#223]
**Describe the bug**

For a given line string grid_tessellate with resolution set to 8 is unable to return any results (resolution 7 or 9 allows to get some results).

**To Reproduce**

import org.apache.spark.sql.functions.{col}
import com.databricks.labs.mosaic.functions.MosaicContext
import com.databricks.labs.mosaic.H3
import com.databricks.labs.mosaic.ESRI
import org.apache.spark.sql.functions._

val mosaicContext = MosaicContext.build(H3, ESRI)
mosaicContext.register(spark)
import mosaicContext.functions._

List(("LINESTRING (-120.65246800000001 40.420067, -120.65228800000001 40.420528000000004)"))
.toDF("wkt")
.select(grid_tessellate(col("wkt"), lit(8)))
.show(1, false)

**Expected behavior**
Index ids for hexes covering the line should be returned. 

**Screenshots**

![image](https://user-images.githubusercontent.com/80038669/195596665-4a900abc-4034-4ff5-a68d-b8b1704ad99f.png)

**Additional context**
Databricks 10.4 LTS (Scala 2.12, Spark version 3.2.1)
mosaic_0_3_0_jar_with_dependencies.jar

The line ends near hex edge.

**Comment by edurdevic** [comment]
Thanks for reporting this. We are taking a look now.

**Comment by edurdevic** [comment]
Indeed there was an issue when the first point of the line would be on the cell boundary. That should be fixed by the PR #230 .

Please note that a line with a segment tangent to the cell boundary would end up being decomposed into two disjoint lines. This is because we perform an intersection between the cell polygons and the line, so the segments that lay tangent to the cell boundaries do not topologically intersect any of the cells.
Would this be a problem for your use case @damianrakowski-tomtom?

**Comment by damianrakowski-tomtom** [comment]
Thank you! The issue is not blocking me, so end of the week is fine. The grid_tessellate behavior you described is currently not an issue for me.
