### ISSUE TITLE
Loading rasters to H3 tables

### ISSUE THREAD

**Issue by JimShady** [databrickslabs/mosaic#342]
Hello Databricks. I'm trying to find a tutorial/guide on how to take a raster file (.tif) and turn it into a H3 table which is then stored in our DataLake.

I've found this function in Mosaic:

https://databrickslabs.github.io/mosaic/api/raster-format-readers.html#mos-read-format-raster-to-grid

But it doesn't seem to use a H3 grid system? Does it?

The output of this looks like it might be a H3 grid?

https://databrickslabs.github.io/mosaic/api/raster-functions.html#rst-rastertogridavg

In general, I feel there is a lack of documentation and help with loading rasters to H3 tables. Would really appreciate more on this subject.

Thanks.

**Comment by milos-colic** [comment]
@JimShady Thank you for opening the issue.

Firstly, we apreciate that the docs could be improved and we are planing a rehaul of the docs and to add tutorial section and blog glossary and more. Stay tuned, it should be happening over next few weeks.

As for the raster_to_grid reader, it will use the grid system you have enabled for Mosaic, the default grid is H3, but you can configure other grids. This concept hasnt been re-iterated on the docs page for the reader itself since it is covered in enabling mosaic. But to your point using generic "grid" term may be confusing if someone hasnt read the other page.

Will will add some better notes and links to the reader docs page.

The docs describing the configuration of grids: https://databrickslabs.github.io/mosaic/api/spatial-indexing.html

The output of the raster_to_grid reader is band_id, cell_id, measure. Band_id is omitted in the current docs, since the example had only 1 band, we will update that as well.

I hope this helps.
Also happy to meet you on a call and discuss how would you envisage a more usable docs page and take your feedback onboard. Feel free to email me on: milos.colic@databricks.com and I can schedule something.

I will close the issue since there isnt any bug or code problem associated with it and since the PRs for improving docs are in the pipeline.

KR,
Milos
