### ISSUE TITLE
Null Pointer Exception loading vector files

### ISSUE THREAD

**Issue by bernie-mak** [databrickslabs/mosaic#343]
Java.lang.NullPointerException is thrown when using spark readers for vector formats supported by GDAL OGR drivers.

12.2 LTS ML (includes Apache Spark 3.3.2, Scala 2.12)
mosaic version 0.3.9

Follow the instructions to install mosaic.

Then run code below to try and import a GeoJson as Spark dataframe

import mosaic as mos
mos.enable_mosaic(spark, dbutils)
mos.enable_gdal(spark)

df = (mos.read().format("multi_read_ogr") 
           .option("driverName", "GeoJSON")
           .option("layerNumber", "1")
           .load(source)
    )

Based on the documentation, code should read a GeoJSON into a spark dataframe, instead, it produces a NullPointerException.

Geojson can be successfully red using:

f = (spark.read.format("Json")
    .option("multiline", "true")
    .load(source))

Sample GeoJson being red is below:

{
    "type": "Feature",
    "geometry": {
        "type": "Point",
        "coordinates": [-118.2437, 34.0522]
    },
    "properties": {
        "name": "Los Angeles"
    }
}

**Comment by milos-colic** [comment]
@bernie-mak Thank you for reporting this issue.
The problem occurs due to `option("layerNumber", "1")`
the layers are 0 indexed in this reader.
I will add a note to the documentation. 

Using your options I was able to recreate the exception:
<img width="725" alt="Screenshot 2023-04-19 at 11 59 37" src="https://user-images.githubusercontent.com/75583254/233054778-dfd50394-a13d-41f4-be92-ed7003e5b1bd.png">

When I changed it to "0" all ran fine:
<img width="943" alt="Screenshot 2023-04-19 at 12 01 48" src="https://user-images.githubusercontent.com/75583254/233055240-a210d313-1821-4bb7-9128-2f4792ef0d4f.png">

The default value is 0, so if you remove the layerNumber option it will run correctly as well.

**Comment by milos-colic** [comment]
I am going to close the issue, since there is no real bug, I will add the notes to the documentation to avoid this issue in the future.

KR,
Milos

**Comment by bernie-mak** [comment]
Hey Milos,

Tried the config you suggested and continued to get the null pointer error. I did notice you were reading the file from dbfs though so tried the same and it works. The issue maybe related to reading from ADLS gen 2 cloud storage:


![image](https://user-images.githubusercontent.com/130889042/233215657-5aa2a6fb-8629-4f33-a956-a653f965d70a.png)

Best Regards,
Michael
