### ISSUE TITLE
MosaicFrame has been removed.

### ISSUE THREAD

**Issue by rickamsterdam** [databrickslabs/mosaic#510]
In the changelog it's mentioned

> MosaicAnalyzer functions now accept Spark DataFrames instead of MosaicFrame, which has been removed.

What does this mean for the optimal resolution argument for `grid_tessellateexplode` - how can I calculate this now?

I used to do something like:

```python
from mosaic import MosaicFrame

mosaic_frame = MosaicFrame(geos, "geometry")
optimal_resolution = mosaic_frame.get_optimal_resolution(sample_fraction=0.75)

df.withColumn(
  "mosaic_index",
  mos.grid_tessellateexplode(col("geometry"), lit(optimal_resolution)),
)
```

And I'm not sure how to achieve the same result and couldn't find anything in the docs (would be happy to contribute a docs fix)

**Comment by mjohns-databricks** [comment]
It is now [MosaicAnalyzer](https://github.com/databrickslabs/mosaic/blob/main/src/main/scala/com/databricks/labs/mosaic/sql/MosaicAnalyzer.scala) which accepts a spark DataFrame instead of a custom MosaicFrame (which has been removed); also [Mosaic 0.4.1](https://github.com/databrickslabs/mosaic/releases/tag/v_0.4.1) added back [python](https://github.com/databrickslabs/mosaic/blob/main/python/mosaic/models/analyzer/analyzer.py) bindings to MosaicAnalyzer. For now, recommend you just look at the source for how to use.

**Comment by tony189** [comment]
I'm not able to import the MosaicAnalyzer. It does not exist within mosaic. Is it within mosaicContext?

I can't find any guidance on mosaic's documentation.

Versión 0.4.1 

Can anyone gide me to analyze a dataframe on this versión?
